### ISSUE TITLE
[Task] Update Bike Quantity after Order is submitted in Accounting

### ISSUE THREAD

**Issue by mbousamra** [Pyxsys/SOEN390_19#101]
**Description**
Function that updates the amount of Bikes with a specific ID after an order is submitted in the accounting page.

**Additional Information**
- Requirements or context needed for the task

**Related Issues:** issue1, issue2, '...'

**Comment by Pyxsys** [comment]
* Implementation performed on the POST function route in `Server/src/AccountingRoutes.js`
* `InternalId` attribute removed form submission in favour of dynamically generated ids in BE

**Comment by Pyxsys** [comment]
accidentally closed reopening
