### ISSUE TITLE
[User Story] As a manufacturer of the company, I want to assemble different parts together and produce a bike

### ISSUE THREAD

**Issue by berkbozok** [Pyxsys/SOEN390_19#12]
**Description**
As the manufacturer of the company, I want to be able to interact with the application so I can assemble different parts together and produce a bike. 

**Associated Tasks**
- [ ] Place parts from inventory into assembler
- [x] Use assembler
- [x] Add bike to inventory

**Comment by Pyxsys** [comment]
#63 done.
