### ISSUE TITLE
[User Story]  As a supplier, I want to show the manufacturer of the bike company all the orders made by the clientele

### ISSUE THREAD

**Issue by berkbozok** [Pyxsys/SOEN390_19#16]
**Description**
As a supplier, I want to show the manufacturer of the bike company all the orders made by the clientele, so that the manufacturers will know what to supply.

**Comment by Pyxsys** [comment]
![image](https://user-images.githubusercontent.com/37449731/113378779-d45fb280-9345-11eb-8151-d082bd0ed566.png)
@EliasMalki initial page sketch

**Comment by NathanZiri** [comment]
Completed in sprint 4
