### ISSUE TITLE
Setup and connect DockerHub accounts

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/SOEN390_19#2]
Collaborators must set up a DockerHub account at the following link: [DockerHub.com](https://hub.docker.com/)
When complete, comment on this issue with your Docker ID to be added to the Docker Repo.

**Step 1: Accounts created:**
- [x] Pyxsys
- [x] nirmal864
- [x] NathanZiri
- [x] SekayZ
- [x] Johnzeng9818
- [x] berkbozok
- [x] mbousamra
- [x] MichaelDCristiano 

**Step 2: Added to Repo:**
- [x] Pyxsys
- [x] nirmal864
- [x] NathanZiri
- [x] SekayZ
- [x] Johnzeng9818
- [x] berkbozok
- [x] mbousamra
- [x] MichaelDCristiano 

 *Please check your name when you've completed a step.
_follow-up of issue #1._

**Comment by SekayZ** [comment]
Docker ID: sekay

**Comment by nirmal864** [comment]
Docker ID: nirmal864

**Comment by MichaelDCristiano** [comment]
Docker ID: michaeldcristiano

**Comment by Johnzeng9818** [comment]
Docker ID:laozeng4399

**Comment by mbousamra** [comment]
Docker ID: mbousamra

**Comment by berkbozok** [comment]
Docker ID: berkbozok

**Comment by Pyxsys** [comment]
@NathanZiri's Docker ID: nathanziri
