### ISSUE TITLE
Software Architecture Document

### ISSUE THREAD

**Issue by nirmal864** [Pyxsys/SOEN390_19#28]
Complete Software Architecture Document for sprint 1

**Comment by SekayZ** [comment]
![uml](https://user-images.githubusercontent.com/44130679/106691328-511e1c80-65a1-11eb-844f-e312bf531bbf.png)
![use-case_diagram](https://user-images.githubusercontent.com/44130679/106691346-58ddc100-65a1-11eb-936b-a3761a32f324.png)
![component_diagram](https://user-images.githubusercontent.com/44130679/106691362-5ed3a200-65a1-11eb-9b06-24dee73bae24.png)

**Comment by SekayZ** [comment]
![sequence_diagram](https://user-images.githubusercontent.com/44130679/106840709-aecc6a80-666e-11eb-914a-e61b16f040a5.png)

**Comment by SekayZ** [comment]
![component_diagram](https://user-images.githubusercontent.com/44130679/109085510-d34cbd00-76d7-11eb-9c1a-49b956b961cd.png)

**Comment by SekayZ** [comment]
![uml](https://user-images.githubusercontent.com/44130679/109085593-f7100300-76d7-11eb-8a27-421336f1c491.png)
