### ISSUE TITLE
[TASK] Merge front-end REACT to stackbase branch

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/SOEN390_19#30]
**Description**
Add/implement the existing front-end react login to the existing back-end on the "stackbase" branch.

**Additional Information**
- HTTP requests should be sent to "<root>/users" path.
- Ensure that mongoDB is installed.

**Related Issues:** #4, #6, #5

**Comment by Pyxsys** [comment]
pull request not valid strategy as front-end branch was generated independently and did not branch off of "main".

**Comment by MichaelDCristiano** [comment]
Don't commit node_modules
