### ISSUE TITLE
[Task] Generate business models

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/SOEN390_19#36]
**Description**
Generate models + schemas for use across the project.
The following entities must be included:
- [x] Business
- [x] Clients
- [x] Suppliers

**Additional Information**
- Models should be placed within the appropriate directory in the Server folder :`root/SOEN390_19/Server/src/Models/`

**Related Issues:** #13, #35

**Comment by nirmal864** [comment]
completed
