### ISSUE TITLE
[Task] Unit Testing 

### ISSUE THREAD

**Issue by SekayZ** [Pyxsys/SOEN390_19#40]
**Description**
Generate unit testing for all main features.
- [x] #34 for Inventory
- [ ] #35 for Sales
- [x] #36 for Business

**Related Issues:** issue #34, #35, #36

**Comment by Pyxsys** [comment]
Due to circumstances, Sales + Business unit tests not feasible for sprint 2.
Unit tests for user authentication should be included in issue.
- [x] User Authentication

**Comment by Pyxsys** [comment]
Closing with #53 merge.
