### ISSUE TITLE
[User Story] As a user, I would like to access the ERP using a supplied User Email and password

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/SOEN390_19#5]
**Description**
As a user, I would like to take the given Email and Password supplied to me by my manager to authenticate myself when accessing the ERP system.

**Associated Tasks**
- [x] Authenticate Users access and sign-in

**Related Issues:** #4

**Comment by MichaelDCristiano** [comment]
We are able to log in with a registered username and password.
