### ISSUE TITLE
[User Story] As an DB Administrator, I would like to organize authenticated users into a database

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/SOEN390_19#6]
**Description**
As a DB Administrator, I would like to be able to refer to a DB that contains authentication information of users so that the ERP, developers, managers and users pull authentication data from a common resource.

**Associated Tasks**
- [x] Create employee authentication ER Diagram
- [x] Generate schema

**Related Issues:** #4 #5

**Comment by Pyxsys** [comment]
Database uses NoSQL, ER diagram not applicable.

**Comment by MichaelDCristiano** [comment]
Registering a User with a username, email address, and password functions correctly. User gets added to the DB and we are able to see the data in the DB.
