### ISSUE TITLE
[Task] Integrate CI to project

### ISSUE THREAD

**Issue by NathanZiri** [Pyxsys/SOEN390_19#82]
**Description**
Travis CI, a continuous integration tool should be added for the current sprint.

**Additional Information**
Relevant commits:
fa7128b1463ba167b768fc45f6923d2605704783
685e62421ad479e23eebc80b1074b186efd31a6d
6b170a747f0842ddc2970107349daf005356f294

**Comment by SekayZ** [comment]
Resolved in pull request #84
