### ISSUE TITLE
[User Story] As a user I'd like to access the product on a dedicated site domain

### ISSUE THREAD

**Issue by NathanZiri** [Pyxsys/SOEN390_19#92]
**Description**
The goal is to host the website and database on a servers in order to allow users to access the full site functionality via a URL.

**Associated Tasks**
- [x] Research deployment for the database
- [x] Research deployment for the site
- [x] Deploy database
- [x] Deploy site

**Additional context**
Ideally we will have several different option which we can chose from in order to come to a consensus on what we want to do.

**Comment by Pyxsys** [comment]
Is there a preference for the domain rootname?
(eg. kappindustries.com)

**Comment by Pyxsys** [comment]
6 local branches and who knows how many clusters later, multiple difficulties have arisen with the use of Azure and IBM deployment strategies.

I am willing entertain kubernetes deployments on AWS.

Any devops experience/wisdom would be deeply welcomed.

**Comment by Pyxsys** [comment]
Good news! FE Deployed via Netlify at: https://kappindu.netlify.app/  
FE slated to be able to publish main and soon BE_PreProd Branches
Back end still pending using Heroku.

**Comment by Pyxsys** [comment]
BE deployment achieved through Heroku, subtree used to appease heroku. Deployment done to https://backend-test390.herokuapp.com/
